version: '3.1'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: demodb
      POSTGRES_DB: demodb
    ports:
      - 5432:5432
