spring:
  application:
    name: passkeys-api
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    hikari:
      maximum-pool-size: 5

relying-party:
  display-name: HelioAuth Passkeys API
  hostname: localhost
  allow-origin-port: false
