spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/api
    username: api
    password: password

relying-party:
  allow-origin-port: true

helioauth:
  webauthn:
    cache:
      expiration: 999m
      max-size: 99999