type: object
description: Request to add a new client application
properties:
  name:
    type: string
    description: Name of the new application.
  relyingPartyHostname:
    type: string
    description: Hostname of the application, e.g. example.com
  relyingPartyName:
    type: string
    description: Name of the relying party presented to clients.
