type: object
description: Represents a request to edit an application.
properties:
  name:
    type: string
    description: Name of the application.
  relyingPartyHostname:
    type: string
    description: Hostname of the relying party.
  relyingPartyName:
    type: string
    description: Name of the relying party presented to clients.
