/*
 * Copyright 2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.helioauth.passkeys.api.mapper;

import com.helioauth.passkeys.api.domain.ClientApplication;
import com.helioauth.passkeys.api.generated.models.AddApplicationRequest;
import com.helioauth.passkeys.api.generated.models.Application;
import com.helioauth.passkeys.api.generated.models.ApplicationApiKey;
import com.helioauth.passkeys.api.generated.models.EditApplicationRequest;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingConstants;
import org.mapstruct.MappingTarget;

import java.util.List;

/**
 * @author Viktor Stanchev
 */
@Mapper(componentModel = MappingConstants.ComponentModel.SPRING)
public interface ClientApplicationMapper {
    Application toResponse(ClientApplication clientApplication);

    List<Application> toResponse(List<ClientApplication> clientApplication);

    ApplicationApiKey toApiKeyResponse(ClientApplication clientApplication);

    @Mapping(target = "id", ignore = true) // ID will be generated by the database
    @Mapping(target = "apiKey", ignore = true) // API key is generated in the service
    ClientApplication toClientApplication(AddApplicationRequest request);

    void updateClientApplication(@MappingTarget ClientApplication clientApplication, EditApplicationRequest request);
}
